version: '3.7'

services:
  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    ports:
      - 5001:5000
    # volumes:
      # - ./services/backend:/usr/src/app
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=hahaha
      - ARCH=ssd300
      - PRETRAINED_TYPE=${PRETRAINED_TYPE}
      - CHECKPOINT_DIR=""
      - CHECKPOINT_PATH=./ssd_tf2/models/ssd_epoch_120.h5
      - UPLOAD_FOLDER=/usr/src/app/uploads
      - ANNO_FOLDER=/usr/src/app/annos
      - DETECT_FOLDER=/usr/src/app/detects
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@db:5432/data_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@db:5432/data_test
    depends_on:
      - db

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    # volumes:
      # - ./services/frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost
    depends_on:
      - backend

  db:
    build:
      context: ./services/db
      dockerfile: Dockerfile
    ports:
      - 5433:5432
    volumes:
      - /ssd_fullstack
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
