version: '3.7'

services:
  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile-prod
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=production
      - ARCH=ssd300
      - SECRET_KEY=${SECRET_KEY}
      - PRETRAINED_TYPE=specified
      - CHECKPOINT_DIR=""
      - CHECKPOINT_PATH=./ssd_tf2/models/ssd_epoch_120.h5
      - UPLOAD_FOLDER=/usr/src/app/uploads
      - ANNO_FOLDER=/usr/src/app/annos
      - DETECT_FOLDER=/usr/src/app/detects
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@db:5432/data_prod
      - DATABASE_TEST_URL=postgres://postgres:postgres@db:5432/data_test
    depends_on:
      - db

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile-prod
      args:
        - NODE_ENV=production
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - "8081:80"
    depends_on:
      - backend

  db:
    build:
      context: ./services/db
      dockerfile: Dockerfile
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data: